### ISSUE TITLE
Please add a MUTE bind feature

### ISSUE THREAD

**Issue by SteveSobka** [justinknguyen/BeatBind#4]
I previously used Toasify to control Spotify via keyboard binds.  I use a joystick controller (aurdino) to control a button/knob for audio volume +/- and I would love to also be able to push the button to MUTE Spotify.

In Toastify, I bound the three to keyboard actions, which is fine and would work for me, but really I would love to be able to use a Joystick device to control Spotify.  You can download a great Joystick emulator to test out here: https://github.com/shauleiz/vJoy
There's newer forks that you can access from the original page.

So my feature request is to add a MUTE feature.

**Comment by justinknguyen** [comment]
I can add a mute hotkey, but what's the use case here? Why mute instead of pausing the music?

I'll look into adding joystick inputs sometime also

**Comment by justinknguyen** [comment]
Added the mute hotkey in v1.2.0. See [How Do I Update The App?](https://github.com/justinknguyen/BeatBind#how-do-i-update-the-app) if the app isn't opening for you. It's because the config file format got updated, so if you created a config file before. It'll need to be updated.

https://github.com/justinknguyen/BeatBind/releases/tag/v1.2.0

**Comment by SteveSobka** [comment]
Thanks Justin,

I am a sim racer and I use a button box similar to this:
https://www.apexsimracing.com/products/race-deck
I like to use one of the knobs to manage Spotify (Vol+/Vol-/Mute) as I need
to press it while driving and not looking ;)

I could probably stop it but I was used to mute... Thx for making the
change...

Steve Sobka
***@***.***
+1-818-425-2494
